### ISSUE TITLE
XMLHttpRequest cannot load https://api.dropbox.com/1/account/info. No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by leonzinger** [christiansmith/ngDropbox#4]
Every api request that i am trying to make returns me this exception.

Am i missing something?

**Comment by christiansmith** [comment]
I suspect this may have something to do with your Angular version. Can you tell me more about your environment? Also, I made some commits last night that change the way Dropbox gets configured. If you've reinstalled the bower component since then, you will need to update your app code as well. See the README...

**Comment by leonzinger** [comment]
I am using Angular 1.2.4 version and in the backend it's Ruby on rails.

I have noticed the changes and updated the project with bower.
The authentication proccess is working as expected, but all requests after are getting this exception :(

**Comment by christiansmith** [comment]
1.2.4 should be ok. Looks like a CORS issue. Are you globally altering any headers in your ng app? I can spare a few minutes later tonight or tomorrow on a goog hangout if you need an extra pair of eyes to debug. Will be out of cell range until this evening.
